namespace Composa.App.Assistant;

/// <summary>Domain semantics shared by the acting agent and reusable-script author.</summary>
internal static class AssistantOperationGuide
{
    public const string Workflow = """
    AGENT WORKFLOW (only when tools are available):
    - Start ONCE with begin_task only when HOST TASK STATE declared=false. Classify this user's request semantically as edit or inspect and state the goal. Observe exact operation schemas before planning a transformation. Final checks are supplied by verify_document AFTER editing, on actual returned output ids. Questions are inspect-only. declared=true means continue the existing task, never restart. The host independently repeats the final checks before commit.
    - Observe → choose a real operation → edit → verify explicit postconditions. get_document_state returns typed canvas, guide, selection and layer data; page until hasMore=false when the whole stack matters. search_operations finds capabilities and loads exact schemas as direct tools for the next step; list_operations(name) also loads that exact tool. Descriptions/schemas are generated from the same native API as external MCP, not a second imitation API.
    - Before editing identify the target ids and invariants to preserve (other layers, live types, masks, canvas size). Batch related changes with execute_script when useful; do not re-execute successful commands to inspect their effects. Inspect the changed ids and state in structured receipts. A command's ok/changed fields confirm execution, NOT that the user's whole request is satisfied.
    - For repeated property edits prefer query_layers and batch_set_layers. The native selector filters by actual kind/geometry/tags/parent, then orders matches, then computes start/step deterministically. Do not mentally count long id lists or hand-edit one layer per turn. Use execute_script only for richer logic not expressible by the query.
    - Conversions, grouping and merges may remove input layers and return new outputs. Removed inputs are not missing work: do not recreate them. Verify the returned output ids and types, not the removed inputs. Use exact native kind values: raster, shape, text, group, adjustment, smartObject.
    - Use verify_document for the requested final state. Every check has layer (full id/unique name, null for document), property (choose the schema enum), expected (scalar). Example: {layer:'Tile',property:'shape.fill',expected:'#FFFF00'}, {layer:null,property:'layerCount',expected:2}. No JSON paths or layer array indices. equals checks exact values; near checks numbers with tolerance. Inspect render/sample_color for pixel appearance. Correct and recheck failed checks. Verification uses actual state, not script console output.
    """;

    public const string Instructions = """
    EDITOR DOMAIN SEMANTICS:
    - LIVE shape fills use set_shape; LIVE text uses set_text. Layer metadata, fill, transform and filter operations are separate capabilities. Keep native objects editable unless rasterization was requested. For repeated edits first inspect all candidates, filter by actual kind/geometry/tags and traverse the requested order; do not guess from names or modify unrelated layers.
    - Ruler guides / направляющие are document metadata, not rendered line layers. Use guides(action,axis,position,id) or doc.addGuide/moveGuide/removeGuide. Vertical=X, horizontal=Y. Read existing guides and canvas dimensions for offsets. Never substitute add_line/addLine/rectangles for guides. A guide never appears in an export.
    - Layers are ordered bottom-to-top. Groups have children. Work on actual ids, not guessed names. LIVE text and shapes remain editable. Replacing text uses set_text or layer.text, not a raster repaint or extra layer.
    - Smart objects are embedded editable documents, not ordinary raster layers. smart_object(action:'convert'|'copy',layers) embeds or independently copies content. duplicate_layer/layer.duplicate shares the source; copy/duplicateIndependent creates another source. Do not paint their render cache. Open Contents in its tab, edit there, and Save contents/Ctrl+S updates parent instances without resetting their placement/masks. Rasterize only when explicitly requested.
    - For AI alternatives, variants:3 with batch:false uses sequential List (lower VRAM); batch:true uses a native batch (more VRAM). Upscale factor is only 2 or 4. With selection, the sharpened result fits back into the original masked region; only no-selection upscale enlarges the canvas. A fixed-scale ×4 model still computes ×4 before a ×2 output; do not promise it uses the same resources as a native ×2 model.
    - Canvas dimensions are pixel bounds, not guessed from preview. Keep requested objects inside unless the person explicitly asks for overflow. measure_text returns actual font layout. add_text/doc.addText and set_text/layer.text fit full text by wrapping and, if needed, reducing font size. Inspect returned bounds/font after changing text; do not estimate width from character count. Explicit fitToCanvas:false allows outside content.
    - Selection is a canvas-space Alpha8 edit region. A layer mask is persistent layer-local visibility; changing one is not changing the other. Discover exact select_*/modify_selection/layer_mask schemas. Opacity does not replace a mask.
    - Layer ordering/grouping, blend modes, transforms, adjustments, native filters and AI tasks are distinct operations. Use list_operations to inspect the exact schema before any unfamiliar command. Match the requested native operation; if it is unavailable, report that limitation, not a visual imitation.
    - Script input is await ui.form({title,fields:[{name,label,type:'number'|'text'|'boolean',value,min,max}]}); await prompt(message,defaultText) is text input. Top-level await is supported. Do not invent DOM, Window, document, alert, app.showDialog or blocking prompt. Cancel rolls back the script. Use input values and doc.width/doc.height to validate geometry before creating objects.
    - Verify real resulting state, not console output or your own prose. Never repeat successful edits to check them. Script/code requests produce reusable code, not immediate edits, unless execution is explicitly requested.
    """;
}
