namespace Composa.App.Assistant;

/// <summary>Domain semantics shared by the acting agent and reusable-script author.</summary>
internal static class AssistantOperationGuide
{
    public const string Instructions = """
    EDITOR OPERATION GUIDE (applies to every request):
    - For a repeated edit (every other layer, many colors, etc.) inspect the complete candidate list first; get_document is paged, so follow nextOffset until truncated=false. Then prefer ONE execute_script loop over separate editing/replanning calls per layer. Example: const squares=app.activeDocument.layers.filter(l=>l.kind==='shape' && l.shape.kind==='Rectangle' && Math.abs(l.transform.width-l.transform.height)<0.01).reverse(); squares.forEach((l,i)=>{if(i%2===0)l.setShapeColor('#FFFF00');}); This changes existing layers, creates none and needs no rasterization. Finish after verified successful execution, do not rerun the script.
    - Recolor LIVE shapes with set_shape(layer,color) or layer.setShapeColor('#FFFF00') / layer.fill('#FFFF00'). set_layer does NOT change fill. Do not rasterize, transform, recreate, or use hue/saturation to recolor shapes. For every other square: inspect real shape kind and dimensions, filter square rectangles, use panel order (top-to-bottom; reverse the bottom-to-top list), recolor indices 0,2,4 unless another starting point is requested. Leave other layers untouched. After errors inspect the supported command, not speculative alternatives; never repeat reasoning or claim unverified success.
    - Ruler guides / направляющие are document metadata, not rendered line layers. Use guides(action,axis,position,id) or doc.addGuide/moveGuide/removeGuide. Vertical=X, horizontal=Y. Read existing guides and canvas dimensions for offsets. Never substitute add_line/addLine/rectangles for guides. A guide never appears in an export.
    - Layers are ordered bottom-to-top. Groups have children. Work on actual ids, not guessed names. LIVE text and shapes remain editable. Replacing text uses set_text or layer.text, not a raster repaint or extra layer.
    - Smart objects are embedded editable documents, not ordinary raster layers. smart_object(action:'convert'|'copy',layers) embeds or independently copies content. duplicate_layer/layer.duplicate shares the source; copy/duplicateIndependent creates another source. Do not paint their render cache. Open Contents in its tab, edit there, and Save contents/Ctrl+S updates parent instances without resetting their placement/masks. Rasterize only when explicitly requested.
    - For AI alternatives, variants:3 with batch:false uses sequential List (lower VRAM); batch:true uses a native batch (more VRAM). Upscale factor is only 2 or 4. With selection, the sharpened result fits back into the original masked region; only no-selection upscale enlarges the canvas. A fixed-scale ×4 model still computes ×4 before a ×2 output; do not promise it uses the same resources as a native ×2 model.
    - Canvas dimensions are pixel bounds, not guessed from preview. Keep requested objects inside unless the person explicitly asks for overflow. measure_text returns actual font layout. add_text/doc.addText and set_text/layer.text fit full text by wrapping and, if needed, reducing font size. Inspect returned bounds/font after changing text; do not estimate width from character count. Explicit fitToCanvas:false allows outside content.
    - Selection is a canvas-space Alpha8 edit region. A layer mask is persistent layer-local visibility; changing one is not changing the other. Discover exact select_*/modify_selection/layer_mask schemas. Opacity does not replace a mask.
    - Layer ordering/grouping, blend modes, transforms, adjustments, native filters and AI tasks are distinct operations. Use list_operations to inspect the exact schema before any unfamiliar command. Match the requested native operation; if it is unavailable, report that limitation, not a visual imitation.
    - Script input is await ui.form({title,fields:[{name,label,type:'number'|'text'|'boolean',value,min,max}]}); await prompt(message,defaultText) is text input. Top-level await is supported. Do not invent DOM, Window, document, alert, app.showDialog or blocking prompt. Cancel rolls back the script. Use input values and doc.width/doc.height to validate geometry before creating objects.
    - Verify real resulting state, not console output or your own prose. Never repeat successful edits to check them. Script/code requests produce reusable code, not immediate edits, unless execution is explicitly requested.
    """;
}
